# Generated by Django 5.0.7 on 2024-07-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("pass1", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=4000)),
                ("regdate", models.DateField(auto_now_add=True)),
                ("readcnt", models.IntegerField(default=0)),
                ("file1", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("ser", models.AutoField(primary_key=True, serialize=False)),
                ("num", models.IntegerField(default=0)),
                ("content", models.CharField(max_length=4000)),
                ("regdate", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
